/**
 *
 *
 * Copyright 2018 Diffblue Limited
 *
 * Diffblue Limited licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package edu.uci.ics.crawler4j.tests.robotstxt;

import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import com.diffblue.deeptestutils.Reflector;

public class PathRuleTest {

    @Rule public ExpectedException thrown = ExpectedException.none();

    /* testedClasses: PathRule */

    /*
    * Test generated by Diffblue Deeptest.
    * This test case covers:
    *  - conditional line 34 branch to line 39
    *  - edu/uci/ics/crawler4j/robotstxt/PathRule.java:39: loop: 1 iterations
    *  - iteration 1
    *     - conditional line 40 branch to line 40
    *     - conditional line 42 branch to line 44
    *     - conditional line 44 branch to line 44
    *     - conditional line 45 branch to line 45
    *     - conditional line 45 branch to line 49
    *  - conditional line 86 branch to line 87
    *  - conditional line 92 branch to line 93
    */

    @Test
    public void robotsPatternToRegexpInputNotNullOutputNotNull() {

        // Arrange
        String pattern = "\\";

        // Act
        java.util.regex.Pattern retval =
            edu.uci.ics.crawler4j.robotstxt.PathRule.robotsPatternToRegexp(pattern);

        // Assert result
        Assert.assertNotNull(retval);
        Assert.assertEquals("^\\Q\\\\E.*", Reflector.getInstanceField(retval, "pattern"));
    }
}
