sudo: required

language: java

jdk:
    - openjdk8
    - openjdk11

services:
    - docker

branches:
    only:
        - master

script:
    - ./gradlew testClasses checkstyle

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
